# pylint: skip-file
# Generated by Django 3.2.7 on 2021-10-11 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJobBatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField(db_index=True)),
                ('started', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('parameters', models.TextField(max_length=34359738368)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField(db_index=True)),
                ('started', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('job_index', models.IntegerField(default=1)),
                ('job_count', models.IntegerField(default=1)),
                ('parameters', models.TextField(default='{}', max_length=34359738368)),
                ('report', models.FileField(blank=True, null=True, upload_to='simple_data_export_uploads')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=4096)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('parameters', models.TextField(max_length=34359738368)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_data_export_destinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
